#!/bin/bash

# Shared config
source root.env

# Enabled services
services=(
    caddy

    # Example website redirect
    website

    # Used by other services
    gluetun
    mail
    rss

    # Service list
    #  (enable/disable by commenting)
    nextcloud
    qbittorrent
    jellyfin
    privatebin
    searxng
    gitea
    huginn
    overleaf
    send
    # glances
    vault
    matrix
    # paint
)

# Synthesize config

rm Caddyfile
echo "### Generated by ctl script ###" > Caddyfile
echo >> Caddyfile

overrides_str=""
for service in "${services[@]}"; do

    # source proxy.env first, as there are subdomain/port definitions!
    for env in proxy "$service"; do
        if [ -f "./$service/$env.env" ]; then
            source "./$service/$env.env"
	fi
    done
    overrides_str="$overrides_str -f ./$service/$service.yml"
    
    echo "# $service" >> Caddyfile
    cat "$service/Caddyfile" >> Caddyfile
    echo >> Caddyfile

done
unset env

# Execute

set -xe;
docker compose --project-directory $PWD $overrides_str $@

