services:
  caddy:
    env_file:
      - ./glances/proxy.env

  glances:
    image: nicolargo/glances
    restart: unless-stopped
    container_name: monitor
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"
      - "./glances/config/glances.conf:/glances/conf/glances.conf"
    ports:
      - $GLANCES_WEBUI_PORT:61208
    environment:
      - TZ=${TZ}
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w"
    # Uncomment for GPU compatibilty (Nvidia) inside the container
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    depends_on:
      - caddy
