services:
  caddy:
    env_file:
      - ./vault/proxy.env

  vault:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - $VAULTWARDEN_PORT:80
    volumes:
      - ./vault/data:/data:rw
    environment:
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=${VAULTWARDEN_WEBSOCKET_ENABLED}
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
      - SMTP_HOST=${VAULTWARDEN_SMTP_HOST}
      - SMTP_FROM=${VAULTWARDEN_SMTP_FROM}
      - SMTP_PORT=${VAULTWARDEN_SMTP_PORT}
      - SMTP_SSL=${VAULTWARDEN_SMTP_SSL}
      - SMTP_USERNAME=${VAULTWARDEN_SMTP_USERNAME}
      - SMTP_PASSWORD=${VAULTWARDEN_SMTP_PASSWORD}
      - DOMAIN=${VAULTWARDEN_DOMAIN}
    depends_on:
      - caddy

