services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: $DOCKER_USER
    ports:
      - $STREAM_PORT:8096
    volumes:
      - ./jellyfin/data/config:/config
      - ./jellyfin/data/cache:/cache
      - type: bind
        source: $STREAM_MUSIC_DIR
        target: /music
        read_only: true
      - type: bind
        source: $STREAM_SHOWS_DIR
        target: /shows
        read_only: true
      - type: bind
        source: $STREAM_DOWNLOADS_DIR
        target: /downloads
        read_only: true
    restart: 'unless-stopped'
    depends_on:
      - caddy

  caddy:
    env_file:
      - ./jellyfin/proxy.env
