services:
  huginn:
    image: ghcr.io/huginn/huginn
    restart: unless-stopped
    container_name: huginn
    ports:
      - $HUGINN_PORT:3000
    volumes:
      - ./huginn/data:/var/lib/mysql
    env_file:
      - ./huginn/huginn_conf.env
    depends_on:
      caddy:
        condition: service_started
      mail:
        condition: service_started

  caddy:
    env_file:
      - ./huginn/proxy.env

