services:
  paint:
    image: lovasoa/wbo
    container_name: paint
    volumes:
      - ./paint/data:/opt/app/server-data
    ports:
      - "$PAINT_PORT:80"
    build:
      context: .
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
    depends_on:
      - caddy

  caddy:
    env_file:
      - ./paint/proxy.env

